spring.application.name=Odiro

# Server Configuration
server.port=8080

# API URL
kakao.api.url=https://dapi.kakao.com/v2/local/search/keyword.json
naver.api.url=https://openapi.naver.com/v1/search/local.json

# API Info
kakao.api.key=3b9a63a9e9923702cbc91576065df9b6
naver.client.id=r5zXVpJb7khGbtgKfqxP
naver.client.secret=e8Gv_APR_s

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:mem:placedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect